apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: mar21-objdetection-cibuild
  janus-idp.io/tekton: mar21-objdetection-cibuild
  backstage.io/kubernetes-id: mar21-objdetection-cibuild
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: mar21-objdetection-cibuild
resources:
  - initialize-namespace/
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
