apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: mar21-objdetection-cibuild
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar21-objdetection-cibuild
  name: mar21-objdetection-cibuild
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
