apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mar21-objdetection-cibuild-model-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar21-objdetection-cibuild-model-server
  name: mar21-objdetection-cibuild-model-server
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/instance: mar21-objdetection-cibuild-model-server
