apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mar21-objdetection-cibuild
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/mar21-objdetection-cibuild:09b8a43b7758553072188e0c5ef476ea018a9011@sha256:a2daf20a6f91897d625ed425812d2cf5eb434a91da827c131a35e03d1662dbd9 # use pre-built to bootstrap
          name: app-inference
